update to fit_disc_gamma default arguments
reconhub/epitrix pull request #24
Opened 2019-09-21 16:36 UTC by cwhittaker1000

Suggested solution to Issue #23 - fit_disc_gamma will occasionally fail to converge. Partly this could be due to sub-optimal default parameters for mu_ini and cv_ini which are both currently set to 1. Have updated fit_disc_gamma to use the empirical estimates of the mean and the coefficient of variation for mu_ini and cv_ini in the absence of any specified values.

2019-09-21 16:40 UTC, thibautjombart requested changes
only minor things; do tell us if it passed the tests and checks on your device, pasting the content of your `R.version`

thanks!! :)

2019-09-21 16:40 UTC, thibautjombart commented on R/fit_discrete.R
> +#'   calculated value,
change the comma to a full stop

2019-09-21 16:40 UTC, thibautjombart commented on R/fit_discrete.R
> +    cv_ini <- sd(x, na.rm = TRUE)/mu_ini
add space around operators (here the `/`)

2019-09-21 16:54 UTC, cwhittaker1000 commented
Suggested changes made and incorporated. Getting this error when running devtools::check():

```
 checking examples ... ERROR
  Running examples in 'epitrix-Ex.R' failed
  The error most likely occurred in:
  
  > base::assign(".ptime", proc.time(), pos = "CheckExEnv")
  > ### Name: clean_labels
  > ### Title: Standardise labels
  > ### Aliases: clean_labels
  > 
  > ### ** Examples
  > 
  > 
  > clean_labels("-_-This is; A    WeÏrD**./sêntënce...")
  [1] "this_is_a_weird_sentence"
  > clean_labels("-_-This is; A    WeÏrD**./sêntënce...", sep = ".")
  [1] "this.is.a.weird.sentence"
  > <ERROR: re-encoding failure from encoding 'UTF-8'>
  input <- c("
  + input
  + clean_labels(input)
  + 
  + # Don't transliterate non-latin words
  + clean_labels(input, transformation = "Latin-ASCII")
  Error: unexpected symbol in:
  "# Don't transliterate non-latin words
  clean_labels(input, transformation = "Latin"
  Execution halted
```

RVersion:

```
> R.version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.2                         
year           2018                        
month          12                          
day            20                          
svn rev        75870                       
language       R                           
version.string R version 3.5.2 (2018-12-20)
nickname       Eggshell Igloo  
```

2019-09-22 11:48 UTC, thibautjombart commented
Looks good, except for testing which will need to be added for the new parts of the code.

Checks fail on CI for another reason, see https://github.com/reconhub/epitrix/issues/25

2019-09-23 06:51 UTC, thibautjombart approved these changes
Awesome, thanks, and welcome to the team!

2019-09-23 06:51 UTC, merged